name: api-dep-man-moniter
description: 'Monitor and Verify api dependencies'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --port
    - ${{ inputs.port }}
    - --orgId
    - ${{ inputs.orginizationId }}
    - --projectName
    - ${{ inputs.projectName }}
inputs:
  orginizationId:
    description: 'The organization id of the api dependencies'
    required: true
  port:
    description: 'The port to run the moniter server'
    required: true
  projectName:
    description: 'The project name of the api dependencies'
    required: true