name: 'API Dependency Monitor'
description: 'Monitors API traffic and checks for compatibility with OpenAPI specifications.'
inputs:
  port:
    description: 'Port to run the proxy server on'
    required: true
    default: '8080'
  PATH_TO_API_SPEC:
    description: 'Path to the OpenAPI specification file'
    required: true
    default: './.github/specFiles/sample_api_spec.yaml'
  IS_PROVIDER:
    description: 'Indicates if the repository is a provider'
    required: true
    default: 'false'
  BACKEND_URL:
    description: 'URL of the backend server to validate requests against'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - run: pip install -r ${{ github.action_path }}/requirments.txt
      shell: bash
    - run: python ${{ github.action_path }}/api-dep-moniter.py > /tmp/proxy.log 2>&1 &
      shell: bash
      env:
        PORT: ${{ inputs.port }}
        ORG_ID: ${{ github.repository_owner_id }}
        ORG_NAME: ${{ github.repository_owner }}
        USER_ID: ${{ github.actor_id }}
        USERNAME: ${{ github.actor }}
        REPO_NAME: ${{ github.repository }}
        IS_PROVIDER: ${{ inputs.is_provider }}
        PATH_TO_API_SPEC: ${{ inputs.path_to_api_spec }}
        BACKEND_URL: ${{ inputs.backend_url }}
    - run: sleep 5
      shell: bash
    - run: |
        sudo cp ~/.mitmproxy/mitmproxy-ca-cert.pem /usr/local/share/ca-certificates/mitmproxy.crt || true
        sudo update-ca-certificates
      shell: bash
    - run: |
        echo "HTTP_PROXY=http://localhost:${{ inputs.port }}" >> $GITHUB_ENV
        echo "HTTPS_PROXY=http://localhost:${{ inputs.port }}" >> $GITHUB_ENV
      shell: bash
branding:
  icon: "award"
  color: "blue"