name: moniter-action

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    inputs:
      orgId:
        description: 'Organization ID'
        required: true
      projectName:
        description: 'Project name'
        required: true
      port:
        description: 'Proxy port'
        required: true
        default: '8080'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and run API Dependency Monitor
        uses: ./app
        with:
          orgId: ${{ inputs.orgId }}
          projectName: ${{ inputs.projectName }}
          port: ${{ inputs.port }}