name: API Dependency Monitor
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  api-dep-man-moniter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run API Dependency Monitor
        uses: ./.github/actions/moniter-action
        with:
          orginizationId: ${{ secrets.ORGINIZATION_ID }}
          port: ${{ secrets.PORT }}
          projectName: ${{ secrets.PROJECT_NAME }}