name: Test Action
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Start the proxy via the action
      - uses: ./
        with:
          path_to_api_spec: ${{ vars.PATH_TO_API_SPEC }}
          backend_url: ${{ vars.BACKEND_URL }}

      # Send test requests through the proxy
      - name: Send test HTTP requests through proxy
        run: |
          curl -x http://localhost:8080 http://httpbin.org/get
          curl -x http://localhost:8080 "http://httpbin.org/get?userId=1"
          curl -x http://localhost:8080 -X POST http://httpbin.org/post
          curl -x http://localhost:8080 http://httpbin.org/anything/products
          curl http://httpbin.org/get

      - uses: ./stop_proxy
        if: always()